# Generated by Django 6.0.4 on 2026-06-19 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_savingsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsmodel',
            name='current_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='savings_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expenses.savingsmodel'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings', 'Savings')], max_length=15),
        ),
    ]
