# Generated by Django 6.0.4 on 2026-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_savingsmodel_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
